---
name: Run certification checker

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: cert-ver-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# If Ansible Lint fails due to files unrelated to your collection's
# core functionality, add an .ansible-lint file to the repository root
# that excludes them. Example:
# https://github.com/ansible-collections/partner-certification-checker/blob/main/.ansible-lint

# If there are sanity test failures that cannot be fixed and are allowed
# to ignore (https://docs.ansible.com/projects/lint/rules/sanity/),
# create a sanity ignore file for each affected ansible-core version
# (e.g. tests/sanity/ignore-2.18.txt) with corresponding entries:
# https://docs.ansible.com/projects/ansible/devel/dev_guide/testing/sanity/ignores.html#ignore-file-location
jobs:
  certification:
    uses: oraNod/partner-certification-checker/.github/workflows/certification-reusable.yml@main
    # For details on tested ansible-core branches and Python versions, see:
    # https://github.com/ansible-collections/partner-certification-checker#tested-ansible-core-branches-and-python-versions
    # with:
    #   ansible-core-version: '2.18.0'
    #   collection-root: 'ansible_collections/junipernetworks/junos'
    #   automation-hub: true
    # Uncomment the lines below if 'automation-hub: true' and you need to
    # install collections from Red Hat Ansible Automation Hub.
    # Requires a repository secret 'AH_TOKEN' containing an Automation Hub token.
    # secrets:
    #   AH_TOKEN: ${{ secrets.AH_TOKEN }}
